### ISSUE TITLE
There is no CentOS Upgrade Tool that works

### ISSUE THREAD

**Issue by gerdesas** [CentOS/docs#10]
The entire section on using the CentOS Upgrade Tool needs to be removed; the tool does not work.

**Comment by quaid** [comment]
Thanks for the tip, I thought it had been made to work. I'll remove the part & submit, will close this issue when done.

**Comment by gerdesas** [comment]
In the event we get community assistance in getting the upgrade tool
working properly it should be easy enough to re-add the section in
question.  Thank you.

**Comment by quaid** [comment]
I ended up changing the content rather than removing it.

Removing the chapter would require renumbering across the whole doc and fixing internal linking.

Instead, I updated the content to reflect that the upgrade tools don't work. This serves the purpose of addressing that topic and answering a question about if to use that tool; if the tool wasn't mentioned it would leave the question open about if the tool should be used or not.

Let me know if you think the language is accurate, strong, and clear enough. Please open a new issue for changes to the new content.

Commit:  https://github.com/CentOS/docs/commit/d7e985d0c11054bacea41b382fc530832975b808

**Comment by pbokoc** [comment]
Just FYI, all redhat-upgrade-tool content has been removed in #12. In the book, sections [5.1. Upgrade or Install?](https://github.com/CentOS/docs/blob/master/asciidoc/7/install-guide/Steps-x86.adoc) (for x86_64) and 10.1 (identical section for ppc64) explain that while RHEL has an upgrade tool, CentOS doesn't and you should reinstall if you want to upgrade to the next major release.
