### ISSUE TITLE
Removing the s390/system Z part

### ISSUE THREAD

**Issue by arrfab** [CentOS/docs#11]
We don't have a s390/system Z architecture port so it should be removed from the doc to not confuse people about upstream arches not covered on our side
Also then wondering about the other arches we support but that aren't in the doc (aarch64/armhfp)

**Comment by quaid** [comment]
It's a different thing writing fresh content to add to the doc than it is to trim out irrelevant parts. If we add new content, we need to test and verify it all works, etc.

So I'd recommend it as an optional task and not a blocker for release.

**Comment by arrfab** [comment]
Yeah, so let's divide this into two parts : 
- removing/trimming the s390/System Z part from the existing doc (so easy part)
- creating another issue to see if we want to also add content for other arches 
Does that work ?

**Comment by quaid** [comment]
OK, let's keep this issue on removing/trimming the s390/System Z parts.

@arrfab Can you create the new issue? I'd like you requesting so we can keep you involved or at least informed.

**Comment by quaid** [comment]
Going through the resolution for issue #10 I realized it is not straight forward to remove entire chapters due to renumbering.

Instead I propose that we empty the chapter and leave an admonition that there is no build for this architecture, and possible link out to a relevant wiki page.

I'll work on this option separately, it's going to take a bit of time to make sure that internal links remain unbroken.

**Comment by pbokoc** [comment]
zSystems/System z content is removed in the asciidoc version of the guide - see #12.
